// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIOObjUR2m08iojBkT8SrXMfADKOPkP5A',
    appId: '1:902016082890:web:1eea24e265e0719afae533',
    messagingSenderId: '902016082890',
    projectId: 'login-page-f86cc',
    authDomain: 'login-page-f86cc.firebaseapp.com',
    storageBucket: 'login-page-f86cc.firebasestorage.app',
    measurementId: 'G-TT3EQZHM0Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAamMyWXAqh7X2fKoUQS4rfjwjVCV6mRx8',
    appId: '1:902016082890:android:df15dee32cb918ecfae533',
    messagingSenderId: '902016082890',
    projectId: 'login-page-f86cc',
    storageBucket: 'login-page-f86cc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA70bnT41K9TVmJVIH9anYg5cnYSxXCjoY',
    appId: '1:902016082890:ios:7322dd65fa547e9efae533',
    messagingSenderId: '902016082890',
    projectId: 'login-page-f86cc',
    storageBucket: 'login-page-f86cc.firebasestorage.app',
    iosBundleId: 'com.example.loginPage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA70bnT41K9TVmJVIH9anYg5cnYSxXCjoY',
    appId: '1:902016082890:ios:7322dd65fa547e9efae533',
    messagingSenderId: '902016082890',
    projectId: 'login-page-f86cc',
    storageBucket: 'login-page-f86cc.firebasestorage.app',
    iosBundleId: 'com.example.loginPage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIOObjUR2m08iojBkT8SrXMfADKOPkP5A',
    appId: '1:902016082890:web:97ce95e3e29a5088fae533',
    messagingSenderId: '902016082890',
    projectId: 'login-page-f86cc',
    authDomain: 'login-page-f86cc.firebaseapp.com',
    storageBucket: 'login-page-f86cc.firebasestorage.app',
    measurementId: 'G-LZ6NCZM9C1',
  );
}
